nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  eslint-utils@*:
    peerDependenciesMeta:
      eslint:
        optional: true

yarnPath: .yarn/releases/yarn-3.1.1.cjs
