import solution from './0389';

/**
 * @author sabertazimi
 * @license MIT
 * @level easy
 * @description find-the-difference
 * You are given two strings s and t.
 * String t is generated by random shuffling string s
 * and then add one more letter at a random position.
 * Return the letter that was added to t.
 */
describe('LeetCode [0389]', () => {
  test('should AC', () => {
    expect(solution('', 'y')).toStrictEqual('y');
    expect(solution('a', 'aa')).toStrictEqual('a');
    expect(solution('ae', 'aea')).toStrictEqual('a');
    expect(solution('abcd', 'abcde')).toStrictEqual('e');
  });
});
