name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1
    - name: Testing
      run: |
          make
          make run
